import Head from "next/head";
import CustomerRoute from "../components/hoc/withCustomerRoute";
import { Banner } from "../components/molecules/Banner";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Portfolio App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    </div>
  );
};

export default CustomerRoute(Home);
